// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto-service.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Data struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string               `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string               `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Reminder             *timestamp.Timestamp `protobuf:"bytes,4,opt,name=reminder,proto3" json:"reminder,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_143bef2d9699bbf8, []int{0}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Data) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Data) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Data) GetReminder() *timestamp.Timestamp {
	if m != nil {
		return m.Reminder
	}
	return nil
}

type CreateRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Data                 *Data    `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_143bef2d9699bbf8, []int{1}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateRequest) GetData() *Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type CreateResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_143bef2d9699bbf8, []int{2}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CreateResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type LoginRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Data                 *Data    `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_143bef2d9699bbf8, []int{3}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *LoginRequest) GetData() *Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type LoginResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_143bef2d9699bbf8, []int{4}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *LoginResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *LoginResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ChangePasswordRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Account              string   `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	NewPassword          string   `protobuf:"bytes,3,opt,name=newPassword,proto3" json:"newPassword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordRequest) Reset()         { *m = ChangePasswordRequest{} }
func (m *ChangePasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordRequest) ProtoMessage()    {}
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_143bef2d9699bbf8, []int{5}
}

func (m *ChangePasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordRequest.Unmarshal(m, b)
}
func (m *ChangePasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordRequest.Marshal(b, m, deterministic)
}
func (m *ChangePasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordRequest.Merge(m, src)
}
func (m *ChangePasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordRequest.Size(m)
}
func (m *ChangePasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordRequest proto.InternalMessageInfo

func (m *ChangePasswordRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ChangePasswordRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *ChangePasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type ChangePasswordResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordResponse) Reset()         { *m = ChangePasswordResponse{} }
func (m *ChangePasswordResponse) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordResponse) ProtoMessage()    {}
func (*ChangePasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_143bef2d9699bbf8, []int{6}
}

func (m *ChangePasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordResponse.Unmarshal(m, b)
}
func (m *ChangePasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordResponse.Marshal(b, m, deterministic)
}
func (m *ChangePasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordResponse.Merge(m, src)
}
func (m *ChangePasswordResponse) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordResponse.Size(m)
}
func (m *ChangePasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordResponse proto.InternalMessageInfo

func (m *ChangePasswordResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ChangePasswordResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ChangePasswordResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type EraseAccountRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Data                 *Data    `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EraseAccountRequest) Reset()         { *m = EraseAccountRequest{} }
func (m *EraseAccountRequest) String() string { return proto.CompactTextString(m) }
func (*EraseAccountRequest) ProtoMessage()    {}
func (*EraseAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_143bef2d9699bbf8, []int{7}
}

func (m *EraseAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EraseAccountRequest.Unmarshal(m, b)
}
func (m *EraseAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EraseAccountRequest.Marshal(b, m, deterministic)
}
func (m *EraseAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EraseAccountRequest.Merge(m, src)
}
func (m *EraseAccountRequest) XXX_Size() int {
	return xxx_messageInfo_EraseAccountRequest.Size(m)
}
func (m *EraseAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EraseAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EraseAccountRequest proto.InternalMessageInfo

func (m *EraseAccountRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *EraseAccountRequest) GetData() *Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type EraseAccountResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EraseAccountResponse) Reset()         { *m = EraseAccountResponse{} }
func (m *EraseAccountResponse) String() string { return proto.CompactTextString(m) }
func (*EraseAccountResponse) ProtoMessage()    {}
func (*EraseAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_143bef2d9699bbf8, []int{8}
}

func (m *EraseAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EraseAccountResponse.Unmarshal(m, b)
}
func (m *EraseAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EraseAccountResponse.Marshal(b, m, deterministic)
}
func (m *EraseAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EraseAccountResponse.Merge(m, src)
}
func (m *EraseAccountResponse) XXX_Size() int {
	return xxx_messageInfo_EraseAccountResponse.Size(m)
}
func (m *EraseAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EraseAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EraseAccountResponse proto.InternalMessageInfo

func (m *EraseAccountResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *EraseAccountResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *EraseAccountResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*Data)(nil), "v1.Data")
	proto.RegisterType((*CreateRequest)(nil), "v1.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "v1.CreateResponse")
	proto.RegisterType((*LoginRequest)(nil), "v1.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "v1.LoginResponse")
	proto.RegisterType((*ChangePasswordRequest)(nil), "v1.ChangePasswordRequest")
	proto.RegisterType((*ChangePasswordResponse)(nil), "v1.ChangePasswordResponse")
	proto.RegisterType((*EraseAccountRequest)(nil), "v1.EraseAccountRequest")
	proto.RegisterType((*EraseAccountResponse)(nil), "v1.EraseAccountResponse")
}

func init() { proto.RegisterFile("proto-service.proto", fileDescriptor_143bef2d9699bbf8) }

var fileDescriptor_143bef2d9699bbf8 = []byte{
	// 416 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0xbf, 0x6f, 0xd4, 0x30,
	0x14, 0x56, 0x72, 0x07, 0x4d, 0x5f, 0xda, 0x53, 0xeb, 0x16, 0x08, 0x16, 0x12, 0x51, 0xa6, 0x5b,
	0x48, 0xd5, 0xab, 0xd4, 0x11, 0x54, 0x95, 0x8a, 0x85, 0xa1, 0x18, 0x06, 0xc4, 0xe6, 0x26, 0x8f,
	0xd4, 0x52, 0x13, 0x07, 0xdb, 0xb9, 0xae, 0x4c, 0xfc, 0xdd, 0x28, 0x8e, 0x73, 0x4a, 0x20, 0x5d,
	0x4e, 0xb7, 0xf9, 0x7b, 0x3f, 0xbe, 0xf7, 0xbd, 0x1f, 0x86, 0x93, 0x5a, 0x49, 0x23, 0xdf, 0x69,
	0x54, 0x6b, 0x91, 0x61, 0x6a, 0x11, 0xf1, 0xd7, 0xe7, 0xf4, 0x6d, 0x21, 0x65, 0xf1, 0x80, 0x67,
	0xd6, 0x72, 0xd7, 0xfc, 0x3c, 0x33, 0xa2, 0x44, 0x6d, 0x78, 0x59, 0x77, 0x41, 0xc9, 0x6f, 0x0f,
	0xe6, 0x1f, 0xb9, 0xe1, 0x64, 0x01, 0xbe, 0xc8, 0x23, 0x2f, 0xf6, 0x96, 0x33, 0xe6, 0x8b, 0x9c,
	0x9c, 0xc2, 0x33, 0x2c, 0xb9, 0x78, 0x88, 0xfc, 0xd8, 0x5b, 0xee, 0xb3, 0x0e, 0x10, 0x0a, 0x41,
	0xcd, 0xb5, 0x7e, 0x94, 0x2a, 0x8f, 0x66, 0xd6, 0xb1, 0xc1, 0xe4, 0x12, 0x02, 0x85, 0xa5, 0xa8,
	0x72, 0x54, 0xd1, 0x3c, 0xf6, 0x96, 0xe1, 0x8a, 0xa6, 0x5d, 0xf9, 0xb4, 0x2f, 0x9f, 0x7e, 0xeb,
	0xcb, 0xb3, 0x4d, 0x6c, 0xf2, 0x01, 0x0e, 0xaf, 0x15, 0x72, 0x83, 0x0c, 0x7f, 0x35, 0xa8, 0x0d,
	0x39, 0x82, 0x19, 0xaf, 0x85, 0xd5, 0xb2, 0xcf, 0xda, 0x27, 0x79, 0x03, 0xf3, 0x9c, 0x1b, 0x6e,
	0xb5, 0x84, 0xab, 0x20, 0x5d, 0x9f, 0xa7, 0xad, 0x68, 0x66, 0xad, 0x09, 0x83, 0x45, 0x4f, 0xa0,
	0x6b, 0x59, 0x69, 0x9c, 0x60, 0x88, 0x60, 0x4f, 0x37, 0x59, 0x86, 0x5a, 0x5b, 0x92, 0x80, 0xf5,
	0xd0, 0x36, 0xaa, 0x94, 0x54, 0xae, 0x9f, 0x0e, 0x24, 0xef, 0xe1, 0xe0, 0xb3, 0x2c, 0x44, 0xb5,
	0xad, 0xa6, 0x2f, 0x70, 0xe8, 0xf2, 0x77, 0x26, 0x09, 0xe1, 0xc5, 0xf5, 0x3d, 0xaf, 0x0a, 0xbc,
	0x75, 0x13, 0x7f, 0x5a, 0x5b, 0x04, 0x7b, 0x3c, 0xcb, 0x64, 0x53, 0x19, 0xb7, 0xbe, 0x1e, 0x92,
	0x18, 0xc2, 0x0a, 0x1f, 0x6f, 0xc7, 0x3b, 0x1c, 0x9a, 0x92, 0x1f, 0xf0, 0xf2, 0xdf, 0x32, 0x3b,
	0x6b, 0xe1, 0x06, 0x4e, 0x6e, 0x14, 0xd7, 0x78, 0xd5, 0xa9, 0xd9, 0x76, 0xb8, 0xdf, 0xe1, 0x74,
	0x4c, 0xb3, 0x2b, 0x81, 0xab, 0x3f, 0x3e, 0x84, 0xbc, 0x31, 0xf7, 0x5f, 0xbb, 0x9f, 0x44, 0x2e,
	0xfb, 0xdb, 0x74, 0xa5, 0xc8, 0x71, 0x2b, 0x65, 0x74, 0xae, 0x94, 0x0c, 0x4d, 0x4e, 0xc9, 0x85,
	0x3b, 0x9f, 0x3e, 0xed, 0xa8, 0x8d, 0x19, 0x1e, 0x14, 0x3d, 0x1e, 0x58, 0x5c, 0xd2, 0x27, 0x58,
	0x8c, 0x27, 0x4f, 0x5e, 0x5b, 0xea, 0xa9, 0xa5, 0x53, 0x3a, 0xe5, 0x72, 0x44, 0x57, 0x70, 0x30,
	0x9c, 0x0f, 0x79, 0xd5, 0xc6, 0x4e, 0x0c, 0x9e, 0x46, 0xff, 0x3b, 0x3a, 0x8a, 0xbb, 0xe7, 0xf6,
	0xcb, 0x5e, 0xfc, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x4d, 0x8e, 0xd9, 0xcd, 0x5a, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthServiceClient interface {
	CreateAccount(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	LoginAccount(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordResponse, error)
	EraseAccount(ctx context.Context, in *EraseAccountRequest, opts ...grpc.CallOption) (*EraseAccountResponse, error)
}

type authServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthServiceClient(cc *grpc.ClientConn) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) CreateAccount(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/v1.authService/CreateAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) LoginAccount(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/v1.authService/LoginAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordResponse, error) {
	out := new(ChangePasswordResponse)
	err := c.cc.Invoke(ctx, "/v1.authService/ChangePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) EraseAccount(ctx context.Context, in *EraseAccountRequest, opts ...grpc.CallOption) (*EraseAccountResponse, error) {
	out := new(EraseAccountResponse)
	err := c.cc.Invoke(ctx, "/v1.authService/EraseAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
type AuthServiceServer interface {
	CreateAccount(context.Context, *CreateRequest) (*CreateResponse, error)
	LoginAccount(context.Context, *LoginRequest) (*LoginResponse, error)
	ChangePassword(context.Context, *ChangePasswordRequest) (*ChangePasswordResponse, error)
	EraseAccount(context.Context, *EraseAccountRequest) (*EraseAccountResponse, error)
}

// UnimplementedAuthServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (*UnimplementedAuthServiceServer) CreateAccount(ctx context.Context, req *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAccount not implemented")
}
func (*UnimplementedAuthServiceServer) LoginAccount(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginAccount not implemented")
}
func (*UnimplementedAuthServiceServer) ChangePassword(ctx context.Context, req *ChangePasswordRequest) (*ChangePasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangePassword not implemented")
}
func (*UnimplementedAuthServiceServer) EraseAccount(ctx context.Context, req *EraseAccountRequest) (*EraseAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EraseAccount not implemented")
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.authService/CreateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).CreateAccount(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_LoginAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).LoginAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.authService/LoginAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).LoginAccount(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.authService/ChangePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ChangePassword(ctx, req.(*ChangePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_EraseAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EraseAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).EraseAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.authService/EraseAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).EraseAccount(ctx, req.(*EraseAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.authService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAccount",
			Handler:    _AuthService_CreateAccount_Handler,
		},
		{
			MethodName: "LoginAccount",
			Handler:    _AuthService_LoginAccount_Handler,
		},
		{
			MethodName: "ChangePassword",
			Handler:    _AuthService_ChangePassword_Handler,
		},
		{
			MethodName: "EraseAccount",
			Handler:    _AuthService_EraseAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto-service.proto",
}
